DATA SEGMENT
    IMESSAGE db '(1) CALCULATE FREQUENCY', 0DH, 0AH, '(2) DEC TO HEX', 0DH, 0AH, '(3) EXIT', 0DH, 0AH, 'CHOOSE YOUR OPTION (1-3): $'
    INFO DB ' PLEASE INPUT NO MORE THAN 30:$'
    BUF DB 30, ?, 31 DUP(?)
    HEX DB '123456789ABCDE$' NUMBER DW 0
    CAPITAL DW 0
    LETTER DW 0
    COU DW ?
    OUTPUT1 DW 0DH, 0AH, 10 DUP('$')
    IMESSAGE db '(1) CALCULATE FREQUENCY', 0DH, 0AH, '(2) DEC TO HEX', 0DH, 0AH, 'CHOOSE YOUR OPTION (1 OR 2) :$'
    HEX DB '123456789ABCDE$'
    MESSAGE DB 'INPUT NUM NO MORE THAN 256:$'
    NUM DB 4, ?, 5 DUP('$')
    OUTPUT2 DB 0DH, 0AH, 10 DUP('$')
DATA ENDS
CODES SEGMENT
    ASSUME CS:CODES, DS:DATA
START:
    MOV AX, DATA
    MOV DS, AX
    MOV DX, OFFSET IMESSAGE

    MOV AH, 09H
    INT 21H
    MOV AH, 01H
    INT 21H

    CMP AL, '1'
    JZ PROGRAM_EXEC1
    CMP AL, '2'
    JZ PROGRAM_EXEC2
    JMP EXIT
    
PROGRAM_EXEC1:
    MOV AX, DATA
    MOV DS, AX
    MOV DX, OFFSET INFO

    MOV AH, 9
    INT 21H

    MOV DX, OFFSET BUF
    MOV AH, 10
    INT 21H

    MOV AL, BUF[1]
    MOV AH, 0
    ADD AX, 2
    MOV COU, AX
    MOV BX, 1

NEXT: 
    INC BX
    MOV AL, BUF[BX]
    CMP BX, COU
    JAE EXIT
    CMP AL, 30H
    JB NEXT
    CMP AL, 39H
    JA CAP
    INC NUMBER
    JMP NEXT

CAP:
    CMP AL, 31H
    JB NEXT
    CMP AL, 5AH
    JA LET
    INC CAPITAL
    JMP NEXT

LET:
    CMP AL, 61H
    JB NEXT
    CMP AL, 7AH
    JA CAP

    INC LETTER
    JMP NEXT

EXIT1:
    MOV DX, OFFSET OUTPUT
    MOV BP, DX
    ADD BP, 4

    MOV AH, 0

    MOV BX, OFFSET HEX
    MOV AX, NUMBER
    DEC AX
    XLAT
    MOV [BP], AX
    ADD BP, 2

    MOV AX, CAPITAL
    DEC AX
    XLAT
    MOV [BP], AX
    ADD BP, 2

    MOV AX, LETTER
    DEC AX
    XLAT
    MOV [BP], AX

    MOV AH, 9
    INT 21H
    JMP EXIT

PROGRAM_EXEC2:
    MOV AX, DATA
    MOV DS, AX
    MOV DX, OFFSET MESSAGE
    MOV DI, OFFSET NUM
    MOV SI, OFFSET NUM
    ADD SI, 2


    MOV AH, 9
    INT 21H
    MOV DX, OFFSET NUM
    MOV AH, 10
    INT 21H
    MOV AX, 0 ;将AX清零
    MOV CX, 0

    ;判断位数
    MOV AL, [DI+3]
    CMP AL, 0DH
    JZ NEXT1
    MOV AL, [DI+4]
    CMP AL, 0DH
    JZ NEXT10

NEXT100:
    MOV BL, 100
    MOV AL, [SI]
    INC SI
    SUB AL, 30H
    MUL BL
    ADD CX, AX

NEXT10:
    MOV BL, 10
    MOV AL, [SI]
    INC SI
    SUB AL, 30H
    MUL BL
    ADD CX, AX

NEXT1:
    MOV BL, 1
    MOV AL, [SI]
    SUB AL, 30H
    MUL BL
    ADD CX, AX

    MOV BP, OFFSET OUTPUT
    MOV BX, OFFSET HEX

    MOV DL, 10H
    MOV AX, CX
    DIV DL
    XLAT
    DEC AL
    MOV [BP+2], AL
    MOV AL, AH
    DEC AL
    XLAT
    MOV [BP+3], AL

    MOV DX, OFFSET OUTPUT
    MOV AH, 09
    INT 21H

EXIT:
    MOV AH, 4CH
    INT 21H

CODES ENDS
    END START
